//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARIKART
    {
        public int ID { get; set; }
        public string CARIKOD { get; set; }
        public string UNVAN { get; set; }
        public string ADISOYADI { get; set; }
        public string ADRES { get; set; }
        public string TELEFON { get; set; }
        public string FAKS { get; set; }
        public string ILCE { get; set; }
        public string IL { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string VERGINO { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
