//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATURA
    {
        public int ID { get; set; }
        public Nullable<int> SUBE_ID { get; set; }
        public Nullable<int> CARI_ID { get; set; }
        public Nullable<System.DateTime> FATURATARIHI { get; set; }
        public string FATURANO { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
