//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATURADETAY
    {
        public int ID { get; set; }
        public Nullable<int> FATURA_ID { get; set; }
        public Nullable<int> URUN_ID { get; set; }
        public string BARKOD { get; set; }
        public string URUNADI { get; set; }
        public Nullable<int> KDVORANI { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
        public Nullable<decimal> ARATOPLAM { get; set; }
        public Nullable<decimal> KDVTOPLAM { get; set; }
        public Nullable<decimal> GENELTOPLAM { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
