//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KASA
    {
        public int ID { get; set; }
        public Nullable<int> SICIL_ID { get; set; }
        public Nullable<int> ODEMETIPI_ID { get; set; }
        public string POSISLEMNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<bool> SILINDI { get; set; }
        public string KULLANICIADI { get; set; }
        public Nullable<System.DateTime> SIL_TARIH { get; set; }
        public string SIL_KULLANICIADI { get; set; }
    }
}
