//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KULLANICILAR
    {
        public int ID { get; set; }
        [Display(Name ="Þube")]
        public Nullable<int> SUBE_ID { get; set; }
        [Display(Name = "Kullanýcý Tipi")]
        public Nullable<int> KULLANICITIPI_ID { get; set; }
        [Display(Name = "Kullanýcý Adý")]
        public string KULLANICIADI { get; set; }
        [Display(Name = "Þifre")]
        public string SIFRE { get; set; }
        [Display(Name = "Aktif")]
        public Nullable<bool> AKTIF { get; set; }
        [Display(Name = "Silindi")]
        public Nullable<bool> SILINDI { get; set; }

    }
}
