//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGSAYFA
    {
        public int ID { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string SAYFA_ADI { get; set; }
        public string ACIKLAMA { get; set; }
        public string IP { get; set; }
        public string MAC { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    }
}
