//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KantinContext : DbContext
    {
        public KantinContext()
            : base("name=KantinContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARIKART> CARIKART { get; set; }
        public virtual DbSet<FATURA> FATURA { get; set; }
        public virtual DbSet<FATURADETAY> FATURADETAY { get; set; }
        public virtual DbSet<HARCAMABONUS> HARCAMABONUS { get; set; }
        public virtual DbSet<KASA> KASA { get; set; }
        public virtual DbSet<KULLANICILAR> KULLANICILAR { get; set; }
        public virtual DbSet<KULLANICITIPI> KULLANICITIPI { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<LOGISLEMTIPI> LOGISLEMTIPI { get; set; }
        public virtual DbSet<LOGSAYFA> LOGSAYFA { get; set; }
        public virtual DbSet<MARKA> MARKA { get; set; }
        public virtual DbSet<MENUFIYAT> MENUFIYAT { get; set; }
        public virtual DbSet<MENUTANIM> MENUTANIM { get; set; }
        public virtual DbSet<ODEMETIPI> ODEMETIPI { get; set; }
        public virtual DbSet<OLCUBIRIMI> OLCUBIRIMI { get; set; }
        public virtual DbSet<PARAMETRE> PARAMETRE { get; set; }
        public virtual DbSet<SICILKARTI> SICILKARTI { get; set; }
        public virtual DbSet<SINIF> SINIF { get; set; }
        public virtual DbSet<SIPARIS> SIPARIS { get; set; }
        public virtual DbSet<SIPARISDETAY> SIPARISDETAY { get; set; }
        public virtual DbSet<SiteSenkronlar> SiteSenkronlar { get; set; }
        public virtual DbSet<STOKHAR> STOKHAR { get; set; }
        public virtual DbSet<STOKKARTI> STOKKARTI { get; set; }
        public virtual DbSet<SUBE> SUBE { get; set; }
        public virtual DbSet<URUNGRUBU> URUNGRUBU { get; set; }
        public virtual DbSet<URUNKISIT> URUNKISIT { get; set; }
        public virtual DbSet<YUKLEMEBONUS> YUKLEMEBONUS { get; set; }
    }
}
