//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRE
    {
        public int ID { get; set; }
        public string IP1 { get; set; }
        public string ADI1 { get; set; }
        public string IP2 { get; set; }
        public string ADI2 { get; set; }
        public string IP3 { get; set; }
        public string ADI3 { get; set; }
        public string IP4 { get; set; }
        public string ADI4 { get; set; }
        public Nullable<bool> KART { get; set; }
        public Nullable<bool> PI { get; set; }
        public Nullable<bool> NOGIRISIZNI { get; set; }
        public Nullable<bool> BAKIYE_SMS { get; set; }
        public Nullable<bool> EKSIBAKIYESATIS { get; set; }
        public Nullable<bool> FISYUKLEME { get; set; }
        public Nullable<bool> FISHARCAMA { get; set; }
        public Nullable<bool> YUKLEMEBONUS { get; set; }
        public Nullable<bool> HARCAMABONUS { get; set; }
        public string PARABIRIMI { get; set; }
        public Nullable<bool> YUKLEMESIL { get; set; }
    }
}
