//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SICILKARTI
    {
        public int ID { get; set; }
        public Nullable<int> SUBE_ID { get; set; }
        public Nullable<int> NO { get; set; }
        public string TC { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public Nullable<int> SINIF_ID { get; set; }
        public string CEPTEL { get; set; }
        public Nullable<int> PI_ID { get; set; }
        public Nullable<int> RFKART_ID { get; set; }
        public string VELIADISOYADI { get; set; }
        public string VELICEPTEL { get; set; }
        public Nullable<decimal> HARCAMALIMITI { get; set; }
        public Nullable<decimal> BAKIYE { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
