//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARISDETAY
    {
        public int ID { get; set; }
        public Nullable<int> SUBE_ID { get; set; }
        public int Sip_ID { get; set; }
        public Nullable<int> URUN_ID { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> GENELTUTAR { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
