//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSenkronlar
    {
        public int Id { get; set; }
        public int KayitId { get; set; }
        public string KayitTipi { get; set; }
        public bool YollandiMi { get; set; }
        public bool SilindiMi { get; set; }
    }
}
