//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOKHAR
    {
        public int ID { get; set; }
        public Nullable<int> URUN_ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<decimal> ALISFIYATI { get; set; }
        public string GENELTOPLAM { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
