//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOKKARTI
    {
        public int ID { get; set; }
        public Nullable<int> SUBE_ID { get; set; }
        public string BARKOD { get; set; }
        public string ADI { get; set; }
        public Nullable<int> URUNGRUBU_ID { get; set; }
        public string BIRIM { get; set; }
        public Nullable<int> MARKA_ID { get; set; }
        public Nullable<int> KDVORANI { get; set; }
        public Nullable<bool> KDVDAHIL { get; set; }
        public Nullable<decimal> SATISFIYATI1 { get; set; }
        public Nullable<decimal> SATISFIYATI2 { get; set; }
        public Nullable<int> MAKSTOK { get; set; }
        public Nullable<int> MINSTOK { get; set; }
        public Nullable<int> STOKADET { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
