//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class URUNGRUBU
    {
        public int ID { get; set; }
        [Required]
        [Display(Name = "Ürün Grubu")]
        public string URUNGRUB { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
